#instructions for madlib
print "Enter the part of speech asked for to create a MadLib"

#wait
import time
time.sleep(3)

#input words for madlib with a half second wait after each answer
a = raw_input("Noun: ")
time.sleep(0.5)
b = raw_input("Adjective: ")
time.sleep(0.5)
c = raw_input("Name of a female friend/famous person: ")
time.sleep(0.5)
d = raw_input("A silly word: ")
time.sleep(0.5)
e = raw_input("Noun: ")
time.sleep(0.5)
f = raw_input("Plural noun: ")
time.sleep(0.5)
g = raw_input("Number: ")
time.sleep(0.5)
h = raw_input("Location: ")
time.sleep(0.5)
i = raw_input("Adjective: ")
time.sleep(0.5)
j = raw_input("Body part: ")
time.sleep(0.5)
k = raw_input("Plural animal: ")
time.sleep(0.5)
l = raw_input("Adverb: ")
time.sleep(0.5)
m = raw_input("Verb: ")
time.sleep(0.5)
n = raw_input("Plural body part: ")
time.sleep(0.5)
o = raw_input("ADJ: ")
time.sleep(0.5)
p = raw_input("Noun: ")
time.sleep(0.5)
q = raw_input("Body part: ")
time.sleep(0.5)
r = raw_input("Noun: ")
time.sleep(0.5)
s = raw_input("Name of a male friend/famous person: ")
time.sleep(0.5)
t = raw_input("Adjective: ")
time.sleep(0.5)
u = raw_input("Emotion: ")
time.sleep(0.5)
v = raw_input("Verb: ")
time.sleep(0.5)
w = raw_input("Noun: ")
time.sleep(0.5)
x = raw_input("Verb ending in ing: ")
time.sleep(0.5)
y = raw_input("Adverb: ")
time.sleep(0.5)
z = raw_input("Number: ")
time.sleep(0.5)
a1 = raw_input("Verb ending in ing: ")
time.sleep(0.5)
b1 = raw_input("Number: ")
time.sleep(0.5)
c1 = raw_input("Adjective: ")
time.sleep(0.5)
d1 = raw_input("Adjective: ")
time.sleep(0.5)
e1 = raw_input("Noun: ")
time.sleep(0.5)
f1 = raw_input("Adjective: ")
time.sleep(0.5)
g1 = raw_input("Verb: ")
time.sleep(0.5)
h1 = raw_input("Adjective ending in ly: ")
time.sleep(0.5)
i1 = raw_input("Adjective: ")
time.sleep(0.5)
j1 = raw_input("Adjective: ")
time.sleep(0.5)
k1 = raw_input("Adjective: ")
time.sleep(0.5)
l1 = raw_input("A silly word: ")
time.sleep(0.5)
m1 = raw_input("Adjective: ")
time.sleep(0.5)
n1 = raw_input("Creature: ")
time.sleep(0.5)
o1 = raw_input("Past tense verb: ")
time.sleep(0.5)
p1 = raw_input("Adjective: ")
time.sleep(0.5)
q1 = raw_input("Plural noun: ")
time.sleep(0.5)
r1 = raw_input("Past tense verb: ")
time.sleep(0.5)
s1 = raw_input("Past tense verb:")

#display madlib
time.sleep(1)

#paragraph 1
print "Once upon a "+a+" a "+b+" girl named "+c+" was born into the Land of "+d+". Although no one knew it, she was not a normal "+e+" -- she was magically ADJ. But as they say with great power comes great "+f+". So as she grew up, she was faced with many challenges."
#paragraph 2
print "When she was only "+g+" years old, she was alone in the "+h+"When a flock of "+i+" three "+j+" -ed "+k+" appeared out of no where! She had to "+l+" "+m+" them, until their "+n+" were "+o+"! Luckily, she got away with only "+p+" on her "+q+"."
#paragraph 3
print "A year later, she a "+r+" -call from her BFF, "+s+". He was "+t+" "+u+"; telling her that an evil was trying to "+v+" her "+w+". Together, they protected his "+w+" from it, by "+x+" "+y+" "+z+" times. After this, she became known for her skill in "+a1+"."
#paragraph 4
print "Finally, when she was "+b1+" years old, her "+c1+" powers we're really put to the test. She got a letter from the leader to the "+d1+" "+e1+". Association, explaining that she had been chosen to copmlete a very "+f1+" and important guest. If she failed, the would "+g1+" "+h1+". Being the noble, "+i1+" girl "+c+" was, she took up the task, and "+s+" joined her, bringing along his magical, "+j1+"armor. Together they followed a map into the "+k1+" "+l1+". Cave, where they found a ferocious "+m1+" "+n1+". The battle was long and monsterous, but in the end, "+c+" and "+s+". "+o1+" and threw "+p1+" "+q1+" at the creature. It "+r1+" in pain, and then it was over. They had "+s1+" the world."
